#Section to define paths for the pre-processing
# This section will be used by the scripts under pre_processing
pre:
  start_date: 2022050100
  end_date: 2022053123
  fclen: 48
  vfld_path: "/scratch/ms/dk/nhz/oprint"
  vobs_path: "/scratch/ms/dk/nhz/oprint/OBS4"
  vfld_template:  #include one for each model if they are different. 
    - "vfld"
  params:
    - S10m
    - T2m
    - RH2m
#Section to define paths for the verification
# This section will be used by the scripts under verification
verif:
  by_step: "12h"
  fcst_model:
    - EC9
  lead_time: seq(0, 24, 1)
  fcst_type: "det" #det or eps
  grps: "leadtime"
  fcst_path: "/scratch/ms/dk/nhd/vfld_vobs_sample/FCTABLE"
  obs_path: "/scratch/ms/dk/nhd/vfld_vobs_sample/OBSTABLE"
  verif_path: "/scratch/ms/dk/nhd/verif_results"
#Section to define the paths for the output
# This section will be used by the plotting scripts
post:
  plot_output: "/scratch/ms/dk/nhd/vfld_vobs_sample/plots2"
  rds_path: "/scratch/ms/dk/nhd/verif_rds"
#This section if only for the scorecards
scorecards:
  ref_model: EC9 
  fcst_model: nea40h11
  params: 
    - T2m
    - S10m
    - RH2m
    - Pmsl
